#pragma once
#define _USE_MATH_DEFINES
#include "string_functions.h"
#include "color_consts.h"
#include <cstdint>
#include <cmath>
#include <istream>
#include <functional>
#include <map>
#include <algorithm>
#include <memory>